"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """
[](#9ccbfb)$directory[](#9ccbfb) """

right_format = """$character [](fg:#d3bfe6)$cmd_duration[](fg:#d3bfe6)"""

[cmd_duration]
min_time = 0
format = "[$duration](bg:#d3bfe6 fg:#392a49)"

[character]
format = "$symbol"
success_symbol = ""
error_symbol = "[](fg:#ffb4ab)[](fg:#ffb4ab)"



[fill]
symbol = ''
style = 'bold fg:#9ccbfb'

[directory]
style = "bg:#9ccbfb fg:#003354"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
